# Generated by Django 4.2 on 2023-05-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_productcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcard',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
    ]
